import {
  ArrowRight,
  BarChart4,
  BookOpen,
  Box,
  Building2,
  CheckCircle,
  Clock,
  CreditCard,
  House,
  Laptop,
  Layers,
  LayoutDashboard,
  Moon,
  Settings,
  Shield,
  Sun,
  Users,
  Wallet,
  X,
} from "lucide-react";

export const Icons = {
  arrowRight: ArrowRight,
  barChart: BarChart4,
  building: Building2,
  checkCircle: CheckCircle,
  clock: Clock,
  close: X,
  creditCard: CreditCard,
  dashboard: LayoutDashboard,
  home: BookOpen,
  house: House,
  laptop: Laptop,
  logo: Layers,
  moon: Moon,
  payments: Wallet,
  shield: Shield,
  settings: Settings,
  sun: Sun,
  users: Users,
  unit: Box,
};
